version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  # Scanning project gradle
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
  # Scanning app gradle
  - package-ecosystem: gradle
    directory: /app
    schedule:
      interval: daily